package de.take_weiland.mods.cameracraft.api;

/**
 * <p>Interface implemented on CameraCraft ore generators. Can be used to cancel or modifiy any CameraCraft ore generation using
 * {@link net.minecraftforge.event.terraingen.OreGenEvent.GenerateMinable}. This interface will be implemented on the
 * {@code WorldGenerator}, the event will be fired with {@link net.minecraftforge.event.terraingen.OreGenEvent.GenerateMinable.EventType#CUSTOM}.</p>
 *
 * @author diesieben07
 */
public interface OreGenerator {

    /**
     * <p>The type of ore this generator generates.</p>
     *
     * @return the ore
     */
    Ore getOre();

    /**
     * <p>Types of ores generated by CameraCraft.</p>
     *
     * @author diesieben07
     */
    enum Ore {

        TIN,
        ALKALINE,
        PHOTONIC

    }
}
